<?php
namespace App\Http\Controllers\Api;
use App\Models\Deal;
use App\Models\Listing;
use App\Models\Plan;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class AdminController {
 public function dashboard(Request $r){$impressions=DB::table('ad_events')->where('type','impression')->count();$clicks=DB::table('ad_events')->where('type','click')->count();return response()->json(['users'=>User::where('is_admin',false)->count(),'kyc_pending'=>User::where('is_admin',false)->where('kyc_status','pending')->count(),'kyc_verified'=>User::where('is_admin',false)->where('kyc_status','verified')->count(),'listings_active'=>Listing::where('status','published')->count(),'deals_open'=>Deal::whereNotIn('status',['active','cancelled','closed'])->count(),'deals_active'=>Deal::where('status','active')->count(),'wallet_volume'=>DB::table('wallet_transactions')->where('status','posted')->sum('amount'),'installments_open'=>DB::table('installments')->where('status','pending')->count(),'installments_overdue'=>DB::table('installments')->where('status','pending')->where('due_date','<',today())->count(),'ad_impressions'=>$impressions,'ad_clicks'=>$clicks,'ad_ctr'=>$impressions>0?round(($clicks/$impressions)*100,2):0]);}
 public function users(Request $r){return User::where('is_admin',false)->with(['subscriptions'=>fn($q)=>$q->with('plan')->whereIn('status',['trial','active'])->latest()])->latest()->paginate(30);}
 public function deals(Request $r){return Deal::with(['seller:id,name,email,kyc_status,risk_score,reputation_score','buyer:id,name,email,kyc_status,risk_score,reputation_score','listing','installments'])->latest()->paginate(30);}
 public function listings(Request $r){return Listing::select(['id','public_id','seller_id','category','title','description','price','accepts_trade','status','published_at','expires_at','created_at','updated_at'])->with(['seller:id,name,email,kyc_status'])->latest()->paginate(30);}
 public function wallets(Request $r){return DB::table('wallet_accounts')->join('users','users.id','=','wallet_accounts.user_id')->leftJoin('wallet_transactions','wallet_transactions.wallet_account_id','=','wallet_accounts.id')->groupBy('wallet_accounts.id','users.name','users.email','wallet_accounts.available_balance','wallet_accounts.status')->selectRaw('wallet_accounts.id, users.name, users.email, wallet_accounts.available_balance as balance, wallet_accounts.status, COUNT(wallet_transactions.id) transactions')->orderByDesc('wallet_accounts.id')->paginate(30);}
 public function installments(Request $r){return DB::table('installments')->join('deals','deals.id','=','installments.deal_id')->orderBy('due_date')->select('installments.*','deals.public_id as deal_public_id')->paginate(50);}
 public function campaigns(Request $r){return DB::table('campaigns')->join('advertisers','advertisers.id','=','campaigns.advertiser_id')->select(['campaigns.id','campaigns.advertiser_id','campaigns.name','campaigns.headline','campaigns.cta','campaigns.target_url','campaigns.placement','campaigns.priority','campaigns.starts_at','campaigns.ends_at','campaigns.active','advertisers.name as advertiser'])->selectRaw('CASE WHEN campaigns.media_path IS NULL THEN 0 ELSE 1 END as has_media')->selectSub(fn($q)=>$q->from('ad_events')->whereColumn('ad_events.campaign_id','campaigns.id')->where('type','impression')->selectRaw('COUNT(*)'),'impressions')->selectSub(fn($q)=>$q->from('ad_events')->whereColumn('ad_events.campaign_id','campaigns.id')->where('type','click')->selectRaw('COUNT(*)'),'clicks')->latest('campaigns.id')->paginate(30);}
 public function plans(Request $r){return Plan::withCount(['subscriptions as subscribers_count'=>fn($q)=>$q->whereIn('status',['trial','active']),'subscriptions as trials_count'=>fn($q)=>$q->where('status','trial')])->orderBy('monthly_price')->get();}
}
